name: Terraform Module Linting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      # Run fmt check on module
      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      # Init in module mode (NO backend)
      - name: Terraform init (module mode)
        run: terraform init -backend=false

      # Validate module
      - name: Terraform validate
        run: terraform validate

      # TFLint
      - name: Run TFLint
        run: tflint --recursive
